name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: h00-exercise
      id: h00-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h00-exercise
        setup-command: npm install
        command: npm run test-00
        timeout: 10
        max-score: 100
    - name: h01-exercise
      id: h01-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h01-exercise
        setup-command: npm install
        command: npm run test-01
        timeout: 10
        max-score: 100
    - name: h02-exercise
      id: h02-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h02-exercise
        setup-command: npm install
        command: npm run test-02
        timeout: 10
        max-score: 100
    - name: h03-exercise
      id: h03-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h03-exercise
        setup-command: npm install
        command: npm run test-03
        timeout: 10
        max-score: 100
    - name: h04-exercise
      id: h04-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h04-exercise
        setup-command: npm install
        command: npm run test-04
        timeout: 10
        max-score: 100
    - name: h05-exercise
      id: h05-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h05-exercise
        setup-command: npm install
        command: npm run test-05
        timeout: 10
        max-score: 100
    - name: h06-exercise
      id: h06-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h06-exercise
        setup-command: npm install
        command: npm run test-06
        timeout: 10
        max-score: 100
    - name: h07-exercise
      id: h07-exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: h07-exercise
        setup-command: npm install
        command: npm run test-07
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        H00-EXERCISE_RESULTS: "${{steps.h00-exercise.outputs.result}}"
        H01-EXERCISE_RESULTS: "${{steps.h01-exercise.outputs.result}}"
        H02-EXERCISE_RESULTS: "${{steps.h02-exercise.outputs.result}}"
        H03-EXERCISE_RESULTS: "${{steps.h03-exercise.outputs.result}}"
        H04-EXERCISE_RESULTS: "${{steps.h04-exercise.outputs.result}}"
        H05-EXERCISE_RESULTS: "${{steps.h05-exercise.outputs.result}}"
        H06-EXERCISE_RESULTS: "${{steps.h06-exercise.outputs.result}}"
        H07-EXERCISE_RESULTS: "${{steps.h07-exercise.outputs.result}}"
      with:
        runners: h00-exercise,h01-exercise,h02-exercise,h03-exercise,h04-exercise,h05-exercise,h06-exercise,h07-exercise
